### ISSUE TITLE
can't get it to work - always fails with "unknown option -nocert"

### ISSUE THREAD

**Issue by wizzard0** [wintersteiger/vscode-x509#1]
- open any PEM file
- select entire file or just base64 lines lines between ---begin certificate---

- expected result: some visualization?
- result: error notification:
```
Errors: unknown option -nocert
usage: x509 [-C] [-addreject arg] [-addtrust arg] [-alias] [-CA file]
    [-CAcreateserial] [-CAform der | pem] [-CAkey file]
    [-CAkeyform der | pem] [-CAserial file] [-certopt option]
    [-checkend arg] [-clrext] [-clrreject] [-clrtrust] [-dates]
    [-days arg] [-email] [-enddate] [-extensions section]
    [-extfile file] [-fingerprint] [-hash] [-in file]
```

show-x509 v0.0.1
VS Code 1.76.0 on macOS Ventura 13.2.1 (M1)
```
% where openssl
> /usr/bin/openssl
% openssl version
> LibreSSL 3.3.6
```

**Comment by wintersteiger** [comment]
Thanks for the report! Apparently LibreSSL doesn't support the `-nocert` option. The extension just calls out to the `openssl` binary and assumes it's the normal OpenSSL. (And yes, it just puts the output into a new file editor.)

**Comment by wizzard0** [comment]
Seems so! At the same time I don’t want to replace the default macOS openssl either %)

**Comment by wintersteiger** [comment]
I've added configuration options that let you set the path to the binary and additional arguments, so that should work in most circumstances now.
